apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-restarter
  namespace: <your-namespace>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-restarter-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-restarter-role-binding
subjects:
- kind: ServiceAccount
  name: pod-restarter
  namespace: <your-namespace>
roleRef:
  kind: ClusterRole
  name: pod-restarter-role
  apiGroup: rbac.authorization.k8s.io
